// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu969Ft_b3SH5Z198oOjkPTHVPqz69eY0',
    appId: '1:471229955622:web:95ed6831eb32e2aeed70e7',
    messagingSenderId: '471229955622',
    projectId: 'flash-card-b5664',
    authDomain: 'flash-card-b5664.firebaseapp.com',
    storageBucket: 'flash-card-b5664.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRvCtWU_TTyIWGPoOwDoT7BDFupPluhEo',
    appId: '1:471229955622:android:837426a3beef5f26ed70e7',
    messagingSenderId: '471229955622',
    projectId: 'flash-card-b5664',
    storageBucket: 'flash-card-b5664.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlwx-W1cbz5S49NBwXBQDdU1PT4ij0htI',
    appId: '1:471229955622:ios:927c13f24fa95ac3ed70e7',
    messagingSenderId: '471229955622',
    projectId: 'flash-card-b5664',
    storageBucket: 'flash-card-b5664.appspot.com',
    iosClientId: '471229955622-osgndd13h1gg0fr48mct7odnbpcenqab.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatStartingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlwx-W1cbz5S49NBwXBQDdU1PT4ij0htI',
    appId: '1:471229955622:ios:927c13f24fa95ac3ed70e7',
    messagingSenderId: '471229955622',
    projectId: 'flash-card-b5664',
    storageBucket: 'flash-card-b5664.appspot.com',
    iosClientId: '471229955622-osgndd13h1gg0fr48mct7odnbpcenqab.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatStartingProject',
  );
}
